export default {
    cg: null,
    email: null,
    batch: null,
    branch: null,
    gender: null,
    github: null,
    admin: false,
    resume: null,
    address: null,
    lastName: null,
    backLogs: null,
    semester: null,
    linkedIn: null,
    firstName: null,
    studentID: null,
    marksheet: null,
    dateOfBirth: null,
    marksheet10: null,
    marksheet12: null,
    schoolName10: null,
    schoolName12: null,
    percentage10: null,
    percentage12: null,
    contactNumber: null,

    semesterOptions: [
        '1st Semester',
        '2nd Semester',
        '3rd Semester',
        '4th Semester',
        '5th Semester',
        '6th Semester',
        '7th Semester',
        '8th Semester'
    ],
    
    branchOptions: [
        "Computer Science Engineering",
        "Electronics Engineering",
        "Mechanical Engineering",
        "Electrical Engineering",
        "Civil Engineering",
        "Production Engineering",
        "Metallurgical Engineering",
    ],

    durationOptions: [
        "2 Months",
        "4 Months",
        "6 Months",
        "12 Months"
    ],

    applied: null,
    jobOpenings: null,
    allStudents: null,
    allApplicants: null,
    myApplications: null,
    currentJobOpening: null,
}